name: CI
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
            fetch-depth: 2

    - name: Install Strobes DevSecOps
      run: wget https://triangulum-cli.s3.ap-south-1.amazonaws.com/v1.4.7/linux/triangulum -O ~/triangulum && chmod +x ~/triangulum

    - name: Run Strobes DevSecOps
      run: ~/triangulum --cli --cfg ${GITHUB_WORKSPACE}/.triangulum/git-leaks.yml --debug
